/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package githubgreeter;

public class GitHubGreeter {

  // Write the welcome method here
  public static String welcome(String name) {
      String new_string = ("Welcome to GitHub, " + name );
      return new_string  = ("Welcome to GitHub, " + name );
  }
    // Write the wishes method here
    public static String wishes() {
        String  wishes_string = ("Have a great semester in CSC 241!");
        return wishes_string;
    }

}
