/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package githubgreeter;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class GitHubGreeterTest {

    @Test
    void instantiation() {
        // Check that the greeter object can be instantiated
        GitHubGreeter gg = new GitHubGreeter();
        assertNotNull(gg, "Could not instantiate greeter");
    }

    @Test
    void testWelcome() {
// Test the welcome String
        String expected = "Welcome to GitHub, James.";
        GitHubGreeter gg = new GitHubGreeter();
        String actual = gg.welcome("James");
        assertTrue(actual.equals(expected), "\n\tExpected: " + expected + "\n\t  Actual: " + actual + "\n");
    }

    @Test
    void testWishes() {
// Test the welcome String
        String expected = "Have a great semester in CSC 241!";
        GitHubGreeter gg = new GitHubGreeter();
        String actual = gg.wishes();
        assertTrue(actual.equals(expected), "\n\tExpected: " + expected + "\n\t  Actual: " + actual + "\n");
    }

}
